# Generated by Django 4.0.1 on 2022-01-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacollection',
            name='employeeId',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
